/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class v2_ch12_printf1_Printf1 */

#ifndef _Included_v2_ch12_printf1_Printf1
#define _Included_v2_ch12_printf1_Printf1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     v2_ch12_printf1_Printf1
 * Method:    print
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_v2_ch12_printf1_Printf1_print
  (JNIEnv *, jclass, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
